version: '3.8'
services:
  app:
    image: webdevops/php-dev:8.1-alpine
    command: sh -c 'composer install && bin/console messenger:consume -vv --bus external.bus external'
    working_dir: /app
    environment:
      DATABASE_URL: "mysql://root@db:3306/app?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
    volumes:
      - .:/app
      - ../symfony:/symfony
    depends_on: [db]
    restart: on-failure
  db:
    image: mariadb:10.11.2
    ports: ['33306:3306']
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
